### ISSUE TITLE
install env error

### ISSUE THREAD

**Issue by lfs119** [zhaolongNCU/PocketDTA#1]
hi, Thanks for your awesome work. when I run 'pip install  requirements.txt', I get a error. Can you give me some help
![image](https://github.com/user-attachments/assets/3fb5da28-200c-4999-b5d5-7c07c4b95308)

**Comment by zhaolongNCU** [comment]
Here it looks like the problem is due to your conda. I would suggest that you can install other dependencies without pip install requirements.txt. I would suggest just installing some of the major packages like torch, torch-geometric,rdkit. Because these packages have high dependencies on their version requirements. Other packages can be installed as needed during the actual runtime.
